source 'http://rubygems.org'
source 'http://gemcutter.org'

gem 'sinatra'
gem 'async_sinatra'
gem 'eventmachine', '>= 1.0.0.beta4'
gem 'em-synchrony', '>= 1.0.0'
gem 'em-http-request', '>= 1.0.0.beta4'
gem 'thin'
gem 'json'
gem 'yajl-ruby'
gem 'nokogiri'
gem 'ruby-hmac'